# SQL Schema for Warung Pintar POS
# Run this in your Supabase SQL Editor

-- 1. Create Roles Enum
CREATE TYPE user_role AS ENUM ('admin', 'kasir');

-- 2. Create Profiles Table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  role user_role DEFAULT 'kasir',
  full_name TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Categories Table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  buy_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  sell_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  unit TEXT DEFAULT 'pcs',
  barcode TEXT UNIQUE,
  threshold INTEGER DEFAULT 5,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create Transactions Table
CREATE TABLE transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_no TEXT UNIQUE NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_method TEXT NOT NULL,
  cash_amount DECIMAL(12,2),
  change_amount DECIMAL(12,2),
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create Transaction Details Table
CREATE TABLE transaction_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id UUID REFERENCES transactions(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  qty INTEGER NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL
);

-- 7. Create Stock Logs Table
CREATE TABLE stock_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  change_qty INTEGER NOT NULL,
  type TEXT NOT NULL, -- 'sale', 'adjustment', 'restock'
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_logs ENABLE ROW LEVEL SECURITY;

-- 9. RLS Policies

-- Profiles: Users can read their own profile
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Categories & Products: Everyone authenticated can read, only admins can write
CREATE POLICY "Authenticated users can read categories" ON categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can manage categories" ON categories FOR ALL TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Authenticated users can read products" ON products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can manage products" ON products FOR ALL TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Transactions: Everyone authenticated can create, users can read their own, admins can read all
CREATE POLICY "Authenticated users can create transactions" ON transactions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Users can view own transactions" ON transactions FOR SELECT TO authenticated USING (
  created_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Authenticated users can create transaction details" ON transaction_details FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Users can view transaction details" ON transaction_details FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM transactions WHERE id = transaction_id AND (created_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')))
);

-- Stock Logs: Authenticated users can read, system/admin can write
CREATE POLICY "Authenticated users can read stock logs" ON stock_logs FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can manage stock logs" ON stock_logs FOR ALL TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 10. Triggers for Stock Management

-- Function to handle stock reduction and logging after transaction
CREATE OR REPLACE FUNCTION handle_transaction_stock()
RETURNS TRIGGER AS $$
BEGIN
  -- Reduce stock in products table
  UPDATE products
  SET stock = stock - NEW.qty,
      updated_at = NOW()
  WHERE id = NEW.product_id;

  -- Insert into stock_logs
  INSERT INTO stock_logs (product_id, change_qty, type, notes)
  VALUES (NEW.product_id, -NEW.qty, 'sale', 'Transaction ID: ' || NEW.transaction_id);

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for transaction_details
CREATE TRIGGER after_insert_transaction_detail
AFTER INSERT ON transaction_details
FOR EACH ROW
EXECUTE FUNCTION handle_transaction_stock();

-- 11. Profile creation trigger on Auth Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', 'kasir');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
